import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type ThemeMode = 'light' | 'dark';
export type Language = 'vi' | 'en';

type TranslateOptions = Record<string, string | number>;

type PreferencesContextValue = {
  theme: ThemeMode;
  language: Language;
  setTheme: (theme: ThemeMode) => void;
  setLanguage: (language: Language) => void;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  t: (key: string, options?: TranslateOptions) => string;
};

const storageKeys = {
  theme: 'learning_center_theme',
  language: 'learning_center_language'
};

const vi: Record<string, string> = {
  ACTIVE: 'Đang hoạt động',
  INACTIVE: 'Tạm ngưng',
  LOCKED: 'Đã khóa',
  ENROLLING: 'Tuyển sinh',
  NOT_OPENED: 'Chưa mở',
  POSTPONED: 'Tạm hoãn',
  FINISHED: 'Kết thúc',
  CANCELLED: 'Đã hủy',
  PAID: 'Đã thanh toán',
  PARTIAL: 'Một phần',
  UNPAID: 'Chưa đóng',
  OVERDUE: 'Quá hạn',
  PRESENT: 'Có mặt',
  ABSENT: 'Vắng',
  LATE: 'Đi muộn',
  ADMIN: 'Quản trị',
  STAFF: 'Nhân viên',
  TEACHER: 'Giáo viên',
  STUDENT: 'Học viên',
  CASH: 'Tiền mặt',
  BANK_TRANSFER: 'Chuyển khoản',
  CARD: 'Thẻ',
  SCHEDULED: 'Đã lên lịch',
  COMPLETED: 'Hoàn thành',
  'Quản trị viên': 'Quản trị viên',
  'Nhân viên tư vấn 01': 'Nhân viên tư vấn 01',
  'Nhân viên tư vấn 02': 'Nhân viên tư vấn 02'
};

const en: Record<string, string> = {
  'Nhiệm vụ chính': 'Main tasks',
  'Thống kê & báo cáo': 'Analytics & reports',
  'Quản lý Leads': 'Lead management',
  'Theo dõi tư vấn': 'Consulting follow-up',
  'Tài khoản': 'Accounts',
  'Khách hàng': 'Customers',
  'Đăng ký học': 'Enrollment',
  'Xếp lớp': 'Class placement',
  'Danh sách học viên': 'Student list',
  'Giáo viên': 'Teachers',
  'Học tập': 'Learning',
  'Lớp học': 'Classes',
  'Khóa học': 'Courses',
  'Lịch học': 'Schedules',
  'Lớp của tôi': 'My classes',
  'Điểm danh': 'Attendance',
  'Nhập điểm': 'Scores',
  'Khóa học của tôi': 'My courses',
  'Lịch của tôi': 'My schedule',
  'Điểm của tôi': 'My scores',
  'Tài chính': 'Finance',
  'Thanh toán': 'Payments',
  'Phiếu thu': 'Receipts',
  'Học phí của tôi': 'My tuition',
  'Hỗ trợ': 'Support',
  'Thông báo': 'Notifications',
  'Tài liệu': 'Documents',
  'Báo cáo': 'Reports',
  'Xin chào': 'Hello',
  'Hướng dẫn deal khách hàng': 'Customer deal guide',
  'Hồ sơ': 'Profile',
  'Đăng xuất': 'Log out',
  'Chế độ sáng': 'Light mode',
  'Chế độ tối': 'Dark mode',
  'Đổi ngôn ngữ': 'Switch language',
  'Hủy': 'Cancel',
  'Xác nhận': 'Confirm',
  'Không thể kết nối máy chủ.': 'Cannot connect to server.',
  'Đã xảy ra lỗi.': 'An error occurred.',
  'Tên đăng nhập hoặc mật khẩu không đúng.': 'Username or password is incorrect.',
  'Đăng nhập hệ thống': 'Sign in',
  'Quản lý trung tâm học thêm': 'Tutoring center management',
  'Tên đăng nhập': 'Username',
  'Mật khẩu': 'Password',
  'Đăng nhập': 'Sign in',
  'Đang đăng nhập...': 'Signing in...',
  'Tài khoản mẫu:': 'Demo accounts:',
  'Mật khẩu:': 'Password:',
  'Dashboard': 'Dashboard',
  'Tổng quan vận hành, tuyển sinh, lớp học và học phí.': 'Operational overview for enrollment, classes, and tuition.',
  'Học viên': 'Students',
  'Tổng lớp': 'Total classes',
  'Lớp đang học': 'Active classes',
  'Khoản học phí cần xử lý': 'Tuition to process',
  'Học phí cần xử lý': 'Tuition to process',
  'Doanh thu đã thu': 'Collected revenue',
  'Doanh thu': 'Revenue',
  'Phân tích học viên': 'Student analytics',
  'Theo dõi tăng trưởng học viên, nguồn hồ sơ, trường học và danh sách chi tiết.': 'Track student growth, profile sources, schools, and detailed records.',
  'Phân tích giáo viên': 'Teacher analytics',
  'Theo dõi đội ngũ giáo viên, chuyên môn và lớp được phân công.': 'Track teachers, specializations, and assigned classes.',
  'Phân tích lớp học': 'Class analytics',
  'Theo dõi số lớp, trạng thái lớp và khóa học liên quan.': 'Track class count, class status, and related courses.',
  'Phân tích lớp đang học': 'Active class analytics',
  'Theo dõi các lớp đang vận hành, buổi học và tiến độ đào tạo.': 'Track active classes, sessions, and learning progress.',
  'Phân tích học phí cần xử lý': 'Tuition processing analytics',
  'Theo dõi công nợ, trạng thái thanh toán và hạn đóng học phí.': 'Track receivables, payment status, and due dates.',
  'Phân tích doanh thu': 'Revenue analytics',
  'Theo dõi doanh thu theo thời gian, phương thức thanh toán và phiếu thu.': 'Track revenue over time, payment methods, and receipts.',
  'Ghi danh gần đây': 'Recent enrollments',
  'Xem biểu đồ chi tiết': 'View detailed charts',
  'Lớp': 'Class',
  'Ngày ghi danh': 'Enrollment date',
  'Trạng thái': 'Status',
  'Xuất báo cáo': 'Export report',
  'Chỉ số đang xem': 'Current metric',
  'Ngày': 'Day',
  'Tháng': 'Month',
  'Năm': 'Year',
  'Tổng cộng': 'Total',
  'Kỳ hiện tại': 'Current period',
  'Kỳ trước': 'Previous period',
  'Tăng trưởng': 'Growth',
  'Xu hướng theo {{period}}': 'Trend by {{period}}',
  'Tỷ trọng': 'Breakdown',
  'So sánh từng mốc thời gian': 'Compare each time point',
  'Dữ liệu chi tiết': 'Detailed data',
  'Tìm kiếm': 'Search',
  'Nhập tên, lớp, mã, trạng thái...': 'Enter name, class, code, status...',
  'Lọc theo nhóm': 'Filter by group',
  'Tất cả': 'All',
  'Hiển thị {{shown}}/{{total}}': 'Showing {{shown}}/{{total}}',
  'Kéo xuống để tải thêm 10 dòng...': 'Scroll down to load 10 more rows...',
  'Đã tải hết dữ liệu phù hợp.': 'All matching data has been loaded.',
  'Không có dữ liệu phù hợp bộ lọc.': 'No data matches the filters.',
  'Lịch học tuần': 'Weekly schedule',
  'Lịch học tuần của tôi': 'My weekly schedule',
  'Tương tự Google Calendar, chia theo thứ và khung giờ': 'Google Calendar style, split by weekday and time slot',
  'Giờ': 'Time',
  'CN': 'Sun',
  'Thứ 2': 'Mon',
  'Thứ 3': 'Tue',
  'Thứ 4': 'Wed',
  'Thứ 5': 'Thu',
  'Thứ 6': 'Fri',
  'Thứ 7': 'Sat',
  'Chưa có phòng': 'No room assigned',
  'Quản lý tài khoản': 'Account management',
  'Theo dõi tài khoản người dùng và trạng thái phân quyền.': 'Track user accounts and authorization status.',
  'Quản lý nhân viên': 'Staff management',
  'Danh sách tài khoản nhân viên trung tâm.': 'Center staff account list.',
  'Quản lý học viên': 'Student management',
  'Thêm học viên, tìm nhanh thông tin liên hệ và tình trạng ghi danh.': 'Add students and quickly view contact and enrollment status.',
  'Thêm học viên': 'Add student',
  'Họ tên': 'Full name',
  'Mã học viên': 'Student code',
  'Địa chỉ': 'Address',
  'Tên phụ huynh': 'Parent name',
  'SĐT phụ huynh': 'Parent phone',
  'Quan hệ': 'Relationship',
  'Khoản học phí': 'Tuition items',
  'Quản lý giáo viên': 'Teacher management',
  'Hồ sơ giáo viên, chuyên môn và lớp được phân công.': 'Teacher profiles, specializations, and assigned classes.',
  'Thêm giáo viên': 'Add teacher',
  'Mã giáo viên': 'Teacher code',
  'Bằng cấp': 'Qualification',
  'Khóa học và môn học': 'Courses and subjects',
  'Quản lý danh mục môn học, học phí và số buổi học của từng khóa.': 'Manage subjects, tuition fees, and session counts for each course.',
  'Tạo môn học': 'Create subject',
  'Tên môn': 'Subject name',
  'Mô tả': 'Description',
  'Tạo môn': 'Create subject',
  'Tạo khóa học': 'Create course',
  'Môn học': 'Subject',
  'Chọn môn': 'Select subject',
  'Tên khóa': 'Course name',
  'Khối lớp': 'Grade',
  'Học phí': 'Tuition',
  'Số buổi': 'Sessions',
  'Tạo khóa': 'Create course',
  'Tổng quan khóa học': 'Course overview',
  'Khối': 'Grade',
  'buổi': 'sessions',
  'lớp': 'classes',
  'Quản lý lớp học': 'Class management',
  'Tạo lớp, phân công giáo viên và theo dõi sĩ số.': 'Create classes, assign teachers, and track class size.',
  'Theo dõi danh sách lớp, sĩ số, giáo viên phụ trách và trạng thái vận hành.': 'Track class list, size, assigned teachers, and operating status.',
  'Thêm lớp học': 'Add class',
  'Sửa lớp học': 'Edit class',
  'Nhập tên lớp, khóa học, giáo viên...': 'Enter class name, course, teacher...',
  'Lọc trạng thái': 'Filter status',
  'Lọc khóa học': 'Filter course',
  'Lọc phòng học': 'Filter room',
  'Phòng học': 'Rooms',
  'Chưa gán phòng': 'No room assigned',
  'Chưa có vị trí': 'No location',
  'Một lớp có thể dùng nhiều phòng; một phòng có thể dùng cho nhiều lớp.': 'A class can use multiple rooms; a room can be reused by multiple classes.',
  'chỗ': 'seats',
  'Thao tác': 'Actions',
  'Sửa': 'Edit',
  'Lưu thay đổi': 'Save changes',
  'Tạo lớp học': 'Create class',
  'Chọn khóa': 'Select course',
  'Tên lớp': 'Class name',
  'Sĩ số tối đa': 'Maximum students',
  'Đang tuyển sinh': 'Enrolling',
  'Đang học': 'Active',
  'Tạo lớp': 'Create class',
  'Phân công giáo viên': 'Assign teacher',
  'Chọn lớp': 'Select class',
  'Chọn giáo viên': 'Select teacher',
  'Vai trò': 'Role',
  'Giáo viên chính': 'Main teacher',
  'Phân công': 'Assign',
  'Ghi danh học viên': 'Enroll student',
  'Đăng ký học viên vào lớp và tự động tạo khoản học phí.': 'Enroll students into classes and automatically create tuition items.',
  'Tạo ghi danh': 'Create enrollment',
  'Chọn học viên': 'Select student',
  'Ghi danh': 'Enroll',
  'Tạo lịch học': 'Create schedule',
  'Tạo lịch học và kiểm tra trùng phòng, trùng lịch giáo viên ở backend.': 'Create schedules and validate room or teacher conflicts in the backend.',
  'Lịch làm việc': 'Work calendar',
  'Nhiệm vụ': 'Tasks',
  'Thêm mới': 'Add new',
  'Hôm nay': 'Today',
  'DS ngày': 'Day list',
  'DS tuần': 'Week list',
  'GV Ngày': 'Teacher day',
  'GV Tuần': 'Teacher week',
  'Bộ lọc': 'Filters',
  'Lọc lớp': 'Filter class',
  'Lọc giáo viên': 'Filter teacher',
  'Lọc thứ': 'Filter weekday',
  'Lịch giáo viên theo tuần': 'Teacher weekly schedule',
  'Thêm mới lịch học': 'Add schedule',
  'Phòng': 'Room',
  'Chọn phòng': 'Select room',
  'Thứ': 'Weekday',
  'Bắt đầu': 'Start',
  'Giờ kết thúc': 'End time',
  'Tạo lịch': 'Create schedule',
  'Lịch học trực quan': 'Visual schedule',
  'Quản lý học phí': 'Tuition management',
  'Ghi nhận thanh toán, tạo hóa đơn và theo dõi công nợ.': 'Record payments, create invoices, and track debt.',
  'Thu học phí': 'Collect tuition',
  'Chọn khoản': 'Select item',
  'còn': 'remaining',
  'Ghi chú': 'Note',
  'Ghi nhận thanh toán': 'Record payment',
  'Phải thu': 'Amount due',
  'Đã thu': 'Collected',
  'Báo cáo thống kê': 'Statistics reports',
  'Doanh thu, công nợ, chuyên cần và kết quả học tập.': 'Revenue, debt, attendance, and learning results.',
  'Công nợ': 'Debt',
  'Chuyên cần': 'Attendance',
  'Kết quả học tập': 'Learning results',
  'Tổng số điểm': 'Total scores',
  'Khóa đang học': 'Active courses',
  'Chưa có khóa học': 'No course assigned',
  'Điểm trung bình': 'Average score',
  'Thông báo mới': 'New notifications',
  'Tiến độ': 'Progress',
  'Điểm': 'Score',
  'Xong': 'Done',
  'Còn': 'Remaining',
  'Vào học': 'Enter class',
  'Bài tập tự chọn': 'Optional exercises',
  'Ôn tập nền tảng': 'Foundation review',
  'Bài tập vận dụng': 'Applied exercises',
  'Bài kiểm tra nhanh': 'Quick test',
  'Đề luyện cuối khóa': 'Final practice test',
  'Từ vựng và công thức': 'Vocabulary and formulas',
  'Đã chấm': 'Graded',
  'Đang làm': 'In progress',
  'Độ khó': 'Difficulty',
  'Hoàn tất': 'Completed',
  'Cần nộp': 'Need submission',
  'Xem bài làm': 'View submission',
  'Lớp được phân công': 'Assigned classes',
  'Danh sách lớp, sĩ số và lịch học của giáo viên.': 'Class list, size, and teacher schedule.',
  'Lịch': 'Schedule',
  'Điểm danh học viên': 'Student attendance',
  'Chọn lớp, buổi học và đánh dấu trạng thái từng học viên.': 'Select class, session, and mark attendance status for each student.',
  'Thông tin buổi học': 'Session information',
  'Chọn buổi': 'Select session',
  'Chọn': 'Select',
  'Chọn lớp để hiển thị học viên.': 'Select a class to show students.',
  'Lưu điểm danh': 'Save attendance',
  'Lưu điểm danh thành công.': 'Attendance saved successfully.',
  'Nhập điểm kiểm tra': 'Enter test scores',
  'Tạo bài kiểm tra, nhập điểm và nhận xét học viên.': 'Create exams, enter scores, and add student comments.',
  'Tên bài kiểm tra': 'Exam name',
  'Ngày kiểm tra': 'Exam date',
  'Điểm tối đa': 'Max score',
  'Tạo bài kiểm tra': 'Create exam',
  'Bài kiểm tra': 'Exam',
  'Chọn bài': 'Select exam',
  'Nhận xét': 'Comment',
  'Lưu điểm': 'Save score',
  'Lịch học của tôi': 'My schedule',
  'Lịch học được trình bày theo dạng tuần để dễ quan sát ca học và phòng học.': 'Weekly schedule layout for easier class and room tracking.',
  'Danh sách lịch học': 'Schedule list',
  'Tình trạng học phí': 'Tuition status',
  'Phải đóng': 'Amount due',
  'Đã đóng': 'Paid',
  'Hồ sơ cá nhân': 'Personal profile',
  'Xem hồ sơ': 'View profile',
  'Đóng': 'Close',
  'Tải xuống': 'Download',
  'Nhấn enter để tìm kiếm': 'Press enter to search',
  'Tổng quan học tập': 'Learning overview',
  'Tỷ lệ chuyên cần': 'Attendance rate',
  'Tổng buổi học': 'Total sessions',
  'Đã tham gia': 'Attended',
  'Chưa điểm danh': 'Not marked',
  'Gói dịch vụ': 'Service package',
  'Lịch hẹn': 'Appointments',
  'Thảo luận': 'Discussion',
  'Hóa đơn': 'Invoices',
  'Giao dịch': 'Transactions',
  'Thống kê': 'Statistics',
  'Điểm và đánh giá': 'Scores and reviews',
  'Nội dung': 'Content',
  'Liên hệ': 'Contact',
  'Phiếu thu học phí': 'Tuition receipt',
  'Mã hóa đơn': 'Invoice ID',
  'Ngày lập': 'Issue date',
  'Chi tiết leads': 'Lead details',
  'Theo dõi tư vấn, kiểm tra đầu vào và chuyển đổi đăng ký học.': 'Track consulting, placement tests, and enrollment conversion.',
  'Gửi mail': 'Send email',
  'Hẹn test': 'Schedule test',
  'Chỉnh sửa': 'Edit',
  'Trở lại danh sách': 'Back to list',
  'Chọn lead mẫu': 'Select sample lead',
  'Học sinh': 'Student',
  'Cần tư vấn lại': 'Need follow-up',
  'Đánh giá chất lượng Leads': 'Lead quality assessment',
  'Chốt kèo cao': 'High closing chance',
  'Thông tin liên hệ': 'Contact information',
  'Tổng quan': 'Overview',
  'Hồ sơ chi tiết': 'Detailed profile',
  'Lịch sử tư vấn': 'Consulting history',
  'Kiểm tra đầu vào': 'Placement test',
  'Danh sách leads': 'Lead list',
  'Chưa có SĐT': 'No phone number',
  'Trạng thái lead': 'Lead status',
  'Mới': 'New',
  'Đã liên hệ': 'Contacted',
  'Đã hẹn kiểm tra': 'Test scheduled',
  'Đã kiểm tra': 'Tested',
  'Số điện thoại': 'Phone number',
  'Tư vấn phụ trách': 'Assigned consultant',
  'Nguồn Lead': 'Lead source',
  'Hẹn tư vấn lại khách hàng này': 'Schedule follow-up consultation',
  'Cập nhật trạng thái đăng ký học': 'Update enrollment status',
  'Cập nhật quá trình tư vấn': 'Update consulting process',
  'Chọn lộ trình học cho học viên': 'Choose learning path',
  'Hẹn tư vấn và kiểm tra đầu vào': 'Schedule consultation and placement test',
  'Liên hệ xác nhận thông tin': 'Contact to confirm information',
  'Nhận lead mới': 'New lead received',
  'Kết quả đầu vào': 'Placement result',
  'Chi tiết': 'Details',
  'Ghi chú thêm': 'Add note',
  'Muốn cải thiện kỹ năng tiếng Anh để nâng cao cơ hội nghề nghiệp và giao tiếp tự tin hơn khi đi du lịch quốc tế.': 'Wants to improve English skills for better career opportunities and more confident communication while traveling internationally.',
  'Ưa chuộng học tiếng Anh qua các lớp học trực tuyến và các ứng dụng học ngôn ngữ có tính tương tác cao.': 'Prefers learning English through online classes and highly interactive language learning apps.',
  'Có thể học vào buổi tối và cuối tuần do công việc bận rộn trong tuần.': 'Can study in the evening and on weekends due to a busy weekday schedule.',
  'Đề xuất hành động': 'Recommended action',
  'Lead có nhu cầu học rõ ràng, nên hẹn test trong 24 giờ và đề xuất lớp': 'The lead has a clear learning need; schedule a test within 24 hours and recommend class',
  'phù hợp': 'suitable',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  LOCKED: 'Locked',
  ENROLLING: 'Enrolling',
  NOT_OPENED: 'Not opened',
  POSTPONED: 'Postponed',
  FINISHED: 'Finished',
  CANCELLED: 'Cancelled',
  PAID: 'Paid',
  PARTIAL: 'Partial',
  UNPAID: 'Unpaid',
  OVERDUE: 'Overdue',
  PRESENT: 'Present',
  ABSENT: 'Absent',
  LATE: 'Late',
  ADMIN: 'Admin',
  STAFF: 'Staff',
  TEACHER: 'Teacher',
  STUDENT: 'Student',
  CASH: 'Cash',
  BANK_TRANSFER: 'Bank transfer',
  CARD: 'Card',
  SCHEDULED: 'Scheduled',
  COMPLETED: 'Completed',
  'Quản trị viên': 'System Admin',
  'Nhân viên tư vấn 01': 'Consultant 01',
  'Nhân viên tư vấn 02': 'Consultant 02',
  'Mã': 'Code',
  'Trường': 'School',
  'Điện thoại': 'Phone',
  'Ngày tạo': 'Created date',
  'Chuyên môn': 'Specialization',
  'Số lớp': 'Class count',
  'Khóa': 'Course',
  'Môn': 'Subject',
  'Sĩ số': 'Class size',
  'Buổi học': 'Session',
  'Ngày học': 'Study date',
  'Còn phải thu': 'Remaining',
  'Hạn đóng': 'Due date',
  'Số tiền': 'Amount',
  'Phương thức': 'Method',
  'Ngày thu': 'Payment date',
  'Chưa có trường': 'No school',
  'Chưa có chuyên môn': 'No specialization',
  'Khác': 'Other',
  'Đang tải dữ liệu...': 'Loading data...',
  'Không có dữ liệu': 'No data',
  'Chưa có dữ liệu để hiển thị.': 'There is no data to display yet.',
  'Chi tiết dữ liệu': 'Data details',
  'Thời gian': 'Time',
  'Giá trị': 'Value',
  'Nhóm': 'Group',
  'Tỷ lệ': 'Rate',
  'Đang hoạt động': 'Active',
  'Tạm ngưng': 'Inactive',
  'Đã khóa': 'Locked',
  'Tuyển sinh': 'Enrolling',
  'Chưa mở': 'Not opened',
  'Tạm hoãn': 'Postponed',
  'Kết thúc': 'Finished',
  'Đã hủy': 'Cancelled',
  'Đã thanh toán': 'Paid',
  'Một phần': 'Partial',
  'Chưa đóng': 'Unpaid',
  'Quá hạn': 'Overdue',
  'Có mặt': 'Present',
  'Vắng': 'Absent',
  'Đi muộn': 'Late',
  'Quản trị': 'Admin',
  'Nhân viên': 'Staff'
};

const PreferencesContext = createContext<PreferencesContextValue | undefined>(undefined);

function getInitialTheme(): ThemeMode {
  const stored = localStorage.getItem(storageKeys.theme);
  if (stored === 'light' || stored === 'dark') {
    return stored;
  }
  return window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}

function getInitialLanguage(): Language {
  const stored = localStorage.getItem(storageKeys.language);
  return stored === 'en' ? 'en' : 'vi';
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<ThemeMode>(getInitialTheme);
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.dataset.theme = theme;
    localStorage.setItem(storageKeys.theme, theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem(storageKeys.language, language);
  }, [language]);

  const setTheme = useCallback((nextTheme: ThemeMode) => setThemeState(nextTheme), []);
  const setLanguage = useCallback((nextLanguage: Language) => setLanguageState(nextLanguage), []);
  const toggleTheme = useCallback(() => setThemeState((current) => (current === 'dark' ? 'light' : 'dark')), []);
  const toggleLanguage = useCallback(() => setLanguageState((current) => (current === 'en' ? 'vi' : 'en')), []);

  const t = useCallback(
    (key: string, options?: TranslateOptions) => {
      const dictionary = language === 'en' ? en : vi;
      let value = dictionary[key] ?? key;
      if (options) {
        Object.entries(options).forEach(([name, replacement]) => {
          value = value.replaceAll(`{{${name}}}`, String(replacement));
        });
      }
      return value;
    },
    [language]
  );

  const value = useMemo(
    () => ({
      theme,
      language,
      setTheme,
      setLanguage,
      toggleTheme,
      toggleLanguage,
      t
    }),
    [language, setLanguage, setTheme, t, theme, toggleLanguage, toggleTheme]
  );

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const value = useContext(PreferencesContext);
  if (!value) {
    throw new Error('usePreferences must be used inside PreferencesProvider');
  }
  return value;
}
